### PR TITLE
fix: changed formatting of variable assignments.

### LINKED ISSUE #66: Format helper data into Tidy Format
In helper_create_data.R, make sure <- is used for assignment instead of =. = is used for assignment on line 17: vals = c('cat','dog','lion').

As per review by @andrealee011 in https://github.com/UBC-MDS/software-review/issues/37#issuecomment-600368326

### PR DESCRIPTION
**Pull request by v5y8**
closes #66

### CODE REVIEW

File: tests/testthat/helper_create_data.R [hunk 1]
```diff
@@ -17,13 +17,13 @@ helper_create_data <- function(n){
   vals = c('cat','dog','lion')
```
Comment (sweber15) [inline tests/testthat/helper_create_data.R]:
```suggestion
  vals <- c('cat','dog','lion')
```

File: tests/testthat/helper_create_data.R [hunk 2]
```diff
@@ -17,13 +17,13 @@ helper_create_data <- function(n){
...
-    cat3 = as.character(rbinom(n, 5, 0.4)),
-    cat4 = sample(vals,n,replace=TRUE)
+    num1 <- rexp(n, 3),
+    num2 <- rnorm(n, 2, 2),
+    num3 <- rnorm(n, 10, 3),
+    cat1 <- as.character(rbinom(n, 1, 0.7)),
+    cat2 <- as.character(rpois(n, 1)),
+    cat3 <- as.character(rbinom(n, 5, 0.4)),
+    cat4 <- sample(vals,n,replace=TRUE)
   )
```
Comment (sweber15) [inline tests/testthat/helper_create_data.R]:
```suggestion
    num1 = rexp(n, 3),
    num2 = rnorm(n, 2, 2),
    num3 = rnorm(n, 10, 3),
    cat1 = as.character(rbinom(n, 1, 0.7)),
    cat2 = as.character(rpois(n, 1)),
    cat3 = as.character(rbinom(n, 5, 0.4)),
    cat4 = sample(vals,n,replace=TRUE)
  )
```

I think the checks are failing because these should be = as they are in a tibble function.

**Review by sweber15 — CHANGES_REQUESTED** [review]
The checks are failing with this change, please see comment.

**Comment by v5y8** [comment]
Oh I see, it was line 17. fixed

**Comment by marvinmin** [comment]
I think you might need to remove  ubuntu-16.04 (3.2) and (3.3) in the yaml file. These two checks failed this week for no reason.

**Review by sweber15 — APPROVED** [review]
Changes look good!

**Review by marvinmin — APPROVED** [review]
